### ISSUE TITLE
Fix PR #1304 CI failure (Dynkin classification forward direction)

### ISSUE THREAD

**Issue by kim-em** [kim-em/FormalFrontier-EtingofRepresentationTheory#1317]
## Current state

PR #1304 (`agent/c8a6d382`) has failing CI. It implements a WIP skeleton for the Dynkin classification forward direction (issue #1283). The PR modifies `Theorem_Dynkin_classification.lean`.

**PR:** #1304 "feat: WIP Dynkin classification forward direction skeleton"
**Branch:** `agent/c8a6d382`
**Problem:** CI FAILED (both build checks)

## Deliverables

1. **Fix CI failure in PR #1304:**
   - Check out the PR branch
   - Run `lake build EtingofRepresentationTheory.Chapter6.Theorem_Dynkin_classification` to reproduce the error
   - Fix compilation errors (likely type mismatches, missing imports, or tactic failures)
   - Push fixes to the PR branch
   - Verify CI passes

## Context

This PR is for #1283 (Dynkin classification forward direction). The forward direction is the last sorry in the classification theorem. Fixing CI unblocks merge and further work on this theorem.

This issue modifies 1 file. 1 deliverable x difficulty 1 = product 1.

## Verification

- CI passes on PR #1304
- No new sorries introduced beyond the WIP skeleton
- Progress file written
